// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl5f3gwNF9g9VsUruEzCd_NWRA4021R5U',
    appId: '1:186484070630:web:d3e7170bb397cd42170327',
    messagingSenderId: '186484070630',
    projectId: 'laundry-management-syste-417b7',
    authDomain: 'laundry-management-syste-417b7.firebaseapp.com',
    storageBucket: 'laundry-management-syste-417b7.appspot.com',
    measurementId: 'G-B6J453K7D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6cDf4dT_BiZY2yLyWlUFNTRE-H70-bs',
    appId: '1:186484070630:android:864f09d3b58c6c05170327',
    messagingSenderId: '186484070630',
    projectId: 'laundry-management-syste-417b7',
    storageBucket: 'laundry-management-syste-417b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8hdVTCHNqzVscGIOd6g2-OI1FVYcPm_0',
    appId: '1:186484070630:ios:4e7e5d54793b8f7b170327',
    messagingSenderId: '186484070630',
    projectId: 'laundry-management-syste-417b7',
    storageBucket: 'laundry-management-syste-417b7.appspot.com',
    iosClientId: '186484070630-7adpebkhebc2bsrv5ta4l5dfo87h8qup.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8hdVTCHNqzVscGIOd6g2-OI1FVYcPm_0',
    appId: '1:186484070630:ios:4e7e5d54793b8f7b170327',
    messagingSenderId: '186484070630',
    projectId: 'laundry-management-syste-417b7',
    storageBucket: 'laundry-management-syste-417b7.appspot.com',
    iosClientId: '186484070630-7adpebkhebc2bsrv5ta4l5dfo87h8qup.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryManagementSystem',
  );
}
